// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_tdYpeIoFcgnqtwjaBeGnOZEJ-1Uvoh0',
    appId: '1:299526309095:web:0a2ba84941146c2066ce42',
    messagingSenderId: '299526309095',
    projectId: 'voca-assist-cloud',
    authDomain: 'voca-assist-cloud.firebaseapp.com',
    storageBucket: 'voca-assist-cloud.firebasestorage.app',
    measurementId: 'G-G06GWB29QJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX2u7pQXQAEc30caxUVXTJIDnnSwDcQo8',
    appId: '1:299526309095:android:60b6c83b6618703e66ce42',
    messagingSenderId: '299526309095',
    projectId: 'voca-assist-cloud',
    storageBucket: 'voca-assist-cloud.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuwfS1N3TAeO-PghED1Sz8xVWShD1zfPs',
    appId: '1:299526309095:ios:49b2facfd3c652d766ce42',
    messagingSenderId: '299526309095',
    projectId: 'voca-assist-cloud',
    storageBucket: 'voca-assist-cloud.firebasestorage.app',
    iosBundleId: 'com.example.vocaAssist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuwfS1N3TAeO-PghED1Sz8xVWShD1zfPs',
    appId: '1:299526309095:ios:49b2facfd3c652d766ce42',
    messagingSenderId: '299526309095',
    projectId: 'voca-assist-cloud',
    storageBucket: 'voca-assist-cloud.firebasestorage.app',
    iosBundleId: 'com.example.vocaAssist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_tdYpeIoFcgnqtwjaBeGnOZEJ-1Uvoh0',
    appId: '1:299526309095:web:06fc10bc470fad0766ce42',
    messagingSenderId: '299526309095',
    projectId: 'voca-assist-cloud',
    authDomain: 'voca-assist-cloud.firebaseapp.com',
    storageBucket: 'voca-assist-cloud.firebasestorage.app',
    measurementId: 'G-564KBHZ342',
  );
}
